FROM ubuntu:20.04

# defaut vars
ENV DB_HOST={{mysql_container_name}} \
    DB_DATABASE={{app_db_name}} \
    DB_PASS={{app_db_password}} \
    DB_USER={{app_db_user}} \
    SEED={{seed}}

RUN apt-get update && \
    apt-get install -y software-properties-common
RUN add-apt-repository ppa:ondrej/php
RUN apt update
RUN apt install -y php7.4 \
    php7.4-fpm \
    php7.4-zip \
    php7.4-mbstring \
    php7.4-tokenizer \
    php7.4-mysql \
    php7.4-gd \
    php7.4-xml \
    php7.4-bcmath \
    php7.4-intl \
    php7.4-curl \
    nodejs \
    composer \
    npm
# wtfffffffffffffffffffffffffffffffffffffffffffffffff pq é que tem de ter o -4?????
RUN git clone https://github.com/Hackathonners/swap.git -4
WORKDIR /swap
RUN cp .env.example .env
RUN composer install
RUN npm install
RUN sed -i s/^DB_HOST=127.0.0.1$/DB_HOST=${DB_HOST}/g .env
RUN sed -i s/^DB_DATABASE=homestead$/DB_DATABASE=${DB_DATABASE}/g .env
RUN sed -i s/^DB_USERNAME=homestead$/DB_USERNAME=${DB_USER}/g .env
RUN sed -i s/^DB_PASSWORD=secret$/DB_PASSWORD=${DB_PASS}/g .env
RUN php artisan key:generate
COPY run_script.sh run_script.sh
RUN chmod u+x run_script.sh
EXPOSE 8000

CMD ./run_script.sh