---
- name: sudo add-apt-repository ppa:ondrej/php
  become: yes
  apt_repository:
    repo: ppa:ondrej/php

- name: Update
  become: yes
  apt:
    update_cache: yes

- name: Dependencies
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
  loop: "{{ app_dependencies }}"

- name: Clone Swap's git repository
  git:
    repo: https://github.com/Hackathonners/swap.git
    clone: yes
    dest: /home/{{ ansible_user_id }}/swap
    update: yes

- name: Install Composer
  composer:
    command: install
    working_dir: /home/{{ ansible_user_id }}/swap

- name: Install "swap"
  npm:
    path: /home/{{ ansible_user_id }}/swap

- name: Template a file to /swap/.env
  template:
    src: env_example
    dest: /home/{{ ansible_user_id }}/swap/.env

- name: generate key
  shell: php artisan key:generate
  args:
    chdir: /home/{{ ansible_user_id }}/swap

- name: migrate db
  shell: php artisan migrate
  args:
    chdir: /home/{{ ansible_user_id }}/swap

- name: migrate db
  shell: nohup php artisan serve --host=0.0.0.0 > app_out.log 2>&1 &
  args:
    chdir: /home/{{ ansible_user_id }}/swap

# Falta:
#   ver a cena do mail e REDIS