apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  # property-like keys; each key maps to a simple value
  mysql_allow_empty_password: "true"
  mysql_database: swap
  mysql_user: swapuser

# kubectl apply -f config.yml
# kubectl exec -it mysql-deployment-....... -- mysqladmin --host=0.0.0.0 --user=swapuser --password=123456 status
