---
- name: Create Swap deployment
  kubernetes.core.k8s:
    state: present
    template: swap-deployment.yml

- name: Create Swap service
  kubernetes.core.k8s:
    state: present
    template: swap-service.yml