---
apiVersion: v1
kind: Secret
metadata:
  name: {{ secret_name }}
  namespace: default
type: Opaque
data:
  pass: {{ app_db_password|b64encode }}

# fazer "echo -n '123456' | openssl base64"
# isto vai dar: MTIzNDU2
# e usa-se isso como pass
